### ISSUE TITLE
Issues in Chrome 65

### ISSUE THREAD

**Issue by pale2hall** [asafdav/ng-csv#225]
Hey there,

I'm not sure what has changed, but I'm not getting any errors, or any results in **Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)**.

It seems like it tries to open a new tab, and then the tab goes away instantaneously, but no file is downloaded.  Any known workarounds?

**Comment by clebens** [comment]
I'm getting similar behavior. I was able to properly download the file in Microsoft Edge 41.16299.15.0.

**Comment by krishsharma** [comment]
Getting same concern. Please suggest how can we fix this issue in Chrome version 65.0.3325

**Comment by pale2hall** [comment]
@clebens, ng-csv also still works fine in Firefox too.

**Comment by dirwin517** [comment]
https://github.com/dirwin517/ng-csv

npm i ng-csv2 --save
bower i https://github.com/dirwin517/ng-csv.git#v0.3.7 --save

Is working for me, hopefully that helps

**Comment by pale2hall** [comment]
@dirwin517 Thank you bud!!  My users are going to be happy they don't have to run multiple browsers.  Did you perhaps make a pull request for @asafdav to integrate the changes?

**Comment by Crash--** [comment]
thank you @dirwin517. It fixes Chrome 65 but breaks firefox (at least 59) :(

**Comment by liampcollins** [comment]
Thanks for this @dirwin517  Noticed that there was a bug using this with IE that redirected to another page when downloading the csv. Will submit a PR for a fix I found for it.

**Comment by zeichee** [comment]
npm i ng-csv2 --save did not work for me.
I tried downgrading my chrome to version 64 and it worked again. But this does not entirely solved the problem because eventually, chrome will update back to version 65

**Comment by liampcollins** [comment]
@Crash-- Have submitted a PR to @dirwin517 that should fix the issue with Firefox.

**Comment by Crash--** [comment]
It seems that ng-csv (this one) works again with Chrome 65.

**Comment by dirwin517** [comment]
I'm still seeing the issue with Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) on a MAC
0.3.9 on bower / npm should have @liampcollins fixes and appears to be working in both chrome/firefox

Cherry Picked changes into PR #226

**Comment by fernandorossato** [comment]
thx @dirwin517 it's working again in Google Chrome

**Comment by krishsharma** [comment]
Thanks dirwin. Its fixed in Chrome 65 Version but breaking in Firefox 52.7.3.

**Comment by MukulAmbulgekar** [comment]
It seems this is fixed in **Version 66.0.3359.137**
